require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-erb

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 3.1.2