services:
  web:
    build:
      context: .

    command: bash -c "rails s -b '0.0.0.0'"

    volumes:
      - .:/myapp

    ports:
      - 3000:3000

    depends_on:
      - db

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    tty: true

    stdin_open: true

  db:
    image: postgres:15

    ports:
      - "5432:5432"

    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data: